### PR TITLE
Add a placeholder implementation for non-mobile platforms

### PR DESCRIPTION
**Pull request by swift-kim**
Sets the default value of `ReactiveBlePlatform.instance` to an instance of `_PlaceholderImplementation`, rather than `ReactiveBleMobilePlatform` (current) which is for mobile platforms only. This is necessary so that federated implementations of this plugin (endorsed or not) can be added for non-mobile (desktop) platforms.

The same approach is being used by 1st-party plugin developers as they have decided to [remove default method channel implementations](https://github.com/flutter/flutter/issues/94224) from their platform interface packages. For example: https://github.com/flutter/plugins/blob/2ce625f1a87e4b738f63a6f1f7e3e040e7c0b87f/packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart#L22

After this change, a new platform implementation can be added by providing a static `registerWith` method that is used to register the plugin for that platform on app startup ([documentation](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#dart-platform-implementations)). Here is the example:
- https://github.com/flutter/plugins/blob/2ce625f1a87e4b738f63a6f1f7e3e040e7c0b87f/packages/image_picker/image_picker_windows/pubspec.yaml#L16
- https://github.com/flutter/plugins/blob/2ce625f1a87e4b738f63a6f1f7e3e040e7c0b87f/packages/image_picker/image_picker_windows/lib/image_picker_windows.dart#L51-L54

I personally need this change to add a Tizen platform implementation of this plugin for [our project](https://github.com/flutter-tizen/plugins). Any comments will be appreciated. Thank you!

### CODE REVIEW

**Comment by swift-kim** [comment]
The following PRs will need an update after this change.

- https://github.com/PhilipsHue/flutter_reactive_ble/pull/599
- https://github.com/PhilipsHue/flutter_reactive_ble/pull/544
- https://github.com/PhilipsHue/flutter_reactive_ble/pull/347

**Comment by swift-kim** [comment]
Should I increase the version numbers in `pubspec.yaml`'s and update the `CHANGELOG` files myself if I want to release this change, or is the release done on a regular basis?

**Comment by swift-kim** [comment]
@Taym95 Hi. If you have some time, could you please take a look at this change and give me some advice?

**Comment by Taym95** [comment]
> @Taym95 Hi. If you have some time, could you please take a look at this change and give me some advice?

I will review it today, sorry for not responding quickly

**Comment by swift-kim** [comment]
@Taym95 Hi. Could you review and give some comments?

**Review by Taym95 — APPROVED** [review]
Thank you for contribution, this will be helpful for endorsed package indeed.

**Comment by Taym95** [comment]
> @Taym95 Hi. Could you review and give some comments?

please update your branch

**Comment by swift-kim** [comment]
@Taym95 Sure. I hope there will be a version bump soon after merge so that this change can be released.

**Comment by Taym95** [comment]
> @Taym95 Sure. I hope there will be a version bump soon after merge so that this change can be released.

Yes

**Pull request merged**
