### PR TITLE
Read RSSI

### PR DESCRIPTION
**Pull request by spkersten**
This is based on https://github.com/PhilipsHue/flutter_reactive_ble/pull/596 and the work by @TNorbury and addresses the review comments and adds tests.

### CODE REVIEW

**Review by werediver — APPROVED** [review]
Looks good to me 👍

**Review by Taym95 — APPROVED** [review]

**Comment by arnoschn** [comment]
What is missing here for it to be accepted? What's the Ble Workflow?

**Comment by dreamerchandra** [comment]
any updates?

**Comment by Gufdoor** [comment]
Any updates...?

**Pull request merged**
