### PR TITLE
Update federated-plugin-structure with upstream changes

### PR DESCRIPTION
**Pull request by juliansteenbakker**
I would like to integrate this package in my application, however the missing macOS support is blocking this for me. I would like to add this integration to this package but in order to do that we need to update the federated-plugin-structure to the latest version. After that i can migrate the existing iOS code to macOS (with some small necessary changes) and create a new pull-request to add the macOS package.

### CODE REVIEW

**Comment by remonh87** [comment]
@juliansteenbakker  thanks for notifying me.  For my other package `flutter stripe`. I got some useful insights and I think I will slightly change the structure. Hope to pick it up this week.

**Comment by juliansteenbakker** [comment]
@remonh87 that sounds interesting! I'm maintain several federated plugins like [flutter_secure_storage](https://github.com/mogol/flutter_secure_storage) so i have some experience with this. Right now i upload each change to the specific platform manually which can be a little time consuming so `Melos` sounds good.

I already fixed all the merge conflicts on a local fork, so i can open a new PR to federated-plugin-structure branch with these changes if you like.

**Comment by remonh87** [comment]
@juliansteenbakker  yes please that would be awesome

**Comment by juliansteenbakker** [comment]
Closed in favor of #335

**Pull request closed without merging**
